fix: concurrent multi module code uploads
Problem:

On matrix builds the upload failed due to a name conflict

Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run

Solution:

Make the module name part of the artifact name - if module name is empty it should stay the same.